name: Autograding

on:
  push:
    branches:
      - main  # Запускать тесты при каждом пуше в main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Запуск тестов
      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"
